### ISSUE TITLE
Bug: Unit testing a component that uses ...mapGetters with modules is throwing errors

### ISSUE THREAD

**Issue by ZaeemKhaliq** [vuejs/test-utils#1275]
Hi there.
I am testing a component that uses a module's **getters** from store using `...mapGetters`, but it throws error. However, it works if getters are accessed inside computed property instead of mapGetters.

The store is as follows: -

```
export default store((/* { ssrContext } */) => {
  const Store = createStore({
    state() {
      return {};
    },
    mutations: {},
    actions: {},
    getters: {},
    modules: {
      location: locationModule,
    },

    // enable strict mode (adds overhead!)
    // for dev mode and --debug builds only
    strict: process.env.DEBUGGING,
  });

  return Store;
});
```

The **getters** I am trying to get are inside the **locationModule** as: -

```
const locationModule = {
  namespaced: true,
  state() {
    return {
      // Some code
    };
  },
  getters: {
    currentSpeed(){
      // Some code
    },
    currentAltitude(){
      // Some code
    }
  }
}
```

And I am accessing the getters in the **Cards.vue** component as following: -
```
import { mapGetters } from "vuex";
export default {
  name: "HomeCards",
  computed: {
    ...mapGetters("location", ["currentAltitude", "currentSpeed"]),
  },
};
```

For testing the **Cards.vue,** component I created a test file **Cards.spec.js** as follows: -

```
import { describe, expect, it } from "@jest/globals";
import { mount, shallowMount, RouterLinkStub } from "@vue/test-utils";

import Cards from "../../../../src/components/Home/Body/Cards.vue";
describe("Cards", () => {
  let $store;

  beforeEach(() => {
    $store = {
      getters: {},
      modules: {
        location: {
          namespaced: true,
          getters: {
            currentSpeed: () => jest.fn(),
            currentAltitude: () => jest.fn(),
          },
        },
      },
    };
  });

  it("Should render a value", async () => {
    const wrapper = mount(Cards, {
      global: {
        mocks: {
          $store,
          $t: (msg) => msg,
        },
        stubs: {
          RouterLink: RouterLinkStub,
          QImg: true,
        },
      },
    });

    const value = wrapper.find(".details-block__value-block");

    expect(value.text()).toBeTruthy();
  });
})
```

When executing the test it throws the following error: -

```
Cards › Should render a value

    TypeError: Cannot read property 'location/' of undefined

at getModuleByNamespace (node_modules/vuex/dist/vuex.cjs.js:1351:42)
      at Proxy.mappedGetter (node_modules/vuex/dist/vuex.cjs.js:1238:25)
      at ReactiveEffect.run (node_modules/vue/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
      at ComputedRefImpl.get value [as value] (node_modules/vue/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1075:39)
      at Object.get [as currentSpeed] (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2142:30)
      at Object.get (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5915:27)
      at Proxy.render (src/components/Home/Body/Cards.vue:120:155)
      at renderComponentRoot (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:465:44)
      at ReactiveEffect.componentUpdateFn [as fn] (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4174:57)
      at ReactiveEffect.run (node_modules/vue/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
      at setupRenderEffect (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4300:9)
      at mountComponent (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4083:9)
      at processComponent (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4041:17)
      at patch (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3647:21)  
      at ReactiveEffect.componentUpdateFn [as fn] (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4181:21)
      at ReactiveEffect.run (node_modules/vue/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
      at setupRenderEffect (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4300:9)
      at mountComponent (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4083:9)
      at processComponent (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4041:17)
      at patch (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3647:21)  
      at render (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4785:13) 
      at mount (node_modules/vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3166:25)  
      at Object.app.mount (node_modules/vue/node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1523:23)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7860:18)
      at Object.<anonymous> (test/jest/__tests__/Home/Cards.spec.js:31:21)
```

However, if instead of mapGetters I access getters inside computed property like this: -

```
export default {
  name: "HomeCards",
  computed: {
    currentAltitude() {
      return this.$store.getters["location/currentAltitude"];
    },
    currentSpeed() {
      return this.$store.getters["location/currentSpeed"];
    },
  },
};
```

The test passes successfully.

Why it isn't working with `...mapGetters()` ???

My **package.json** file: -

```
{
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"See package.json => scripts for available tests.\" && exit 0",
    "test:unit:ui": "majestic",
    "test:unit": "jest --updateSnapshot",
    "test:unit:ci": "jest --ci",
    "test:unit:coverage": "jest --coverage",
    "test:unit:watch": "jest --watch",
    "test:unit:watchAll": "jest --watchAll",
    "serve:test:coverage": "quasar serve test/jest/coverage/lcov-report/ --port 8788",
    "concurrently:dev:jest": "concurrently \"quasar dev\" \"jest --watch\""
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "core-js": "^3.6.5",
    "gsap": "^3.8.0",
    "quasar": "^2.0.0",
    "vue": "^3.2.22",
    "vue-i18n": "^9.2.0-beta.22",
    "vuex": "^4.0.1"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.16.5",
    "@quasar/app": "^3.0.0",
    "@quasar/quasar-app-extension-testing-unit-jest": "^3.0.0-alpha.6",
    "eslint": "^8.6.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jest": "^25.3.4",
    "eslint-plugin-vue": "^8.2.0",
    "eslint-webpack-plugin": "^3.1.1",
    "majestic": "^1.7.0",
    "sass-loader": "^12.3.0"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 12.22.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}

```

**Comment by afontcu** [comment]
Hi,

You're testing using a real Vuex store, so the docs would help: [Testing with a Real Vuex Store](https://next.vue-test-utils.vuejs.org/guide/advanced/vuex.html#testing-with-a-real-vuex-store). (In short: you should pass in the store as a plugin, not as a `$store` mock)

**Comment by ZaeemKhaliq** [comment]
> 

This solved the issue. Thanks.
But any explanation for why it wasn't working only with `mapGetters`??? It is working with mock store even if I access a getter directly in template like `{{  $store.getters['location/currentAltitude']  }}`

**Comment by afontcu** [comment]
Glad you solved it! I guess it is because the mock you provided made `$store.getters` work, but it was unable to set and define `mapGetters` (which comes from a real store, not a mock).
