### ISSUE TITLE
Identifier '_interopRequireDefault' has already been declared.

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/test-utils#1400]
**Describe the bug**
```
tests/unit/App.test.js
  ● Test suite failed to run

    SyntaxError: \nw-vue-cli-example\src\App.vue: Identifier '_interopRequireDefault' has already been declared. (41:9)

      39 | var _nw = _interopRequireDefault(require("@/assets/nw.png"));
      40 |
    > 41 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
         |          ^
      42 |
      43 | const _hoisted_1 = {
      44 |   id: "app"

      at instantiate (node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
      at toParseError (node_modules/@babel/parser/src/parse-error.js:58:12)
      at Parser.raise (node_modules/@babel/parser/src/tokenizer/index.js:1763:19)
      at ScopeHandler.checkRedeclarationInScope (node_modules/@babel/parser/src/util/scope.js:153:19)
      at ScopeHandler.declareName (node_modules/@babel/parser/src/util/scope.js:114:12)
      at Parser.registerFunctionStatementId (node_modules/@babel/parser/src/parser/statement.js:1343:16)
      at Parser.parseFunction (node_modules/@babel/parser/src/parser/statement.js:1310:12)
      at Parser.parseFunctionStatement (node_modules/@babel/parser/src/parser/statement.js:746:17)
      at Parser.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:366:21)
      at Parser.parseStatement (node_modules/@babel/parser/src/parser/statement.js:329:17)
```

**To Reproduce**

Occurs in this branch:

* https://github.com/nwutils/nw-vue-cli-example/tree/vue-3

**Expected behavior**

* Test passes

**Related information:**

* `@vue/test-utils` version: 2.0.0-rc.18
* `Vue` version: 3.2.31
* `node` version: 16.14.2
* `npm` version: 8.5.0

**Additional context**

Only place I've found with the exact same error is:

* https://stackoverflow.com/questions/51159447/what-is-interoprequiredefault

**Comment by freakzlike** [comment]
Maybe related to #695

**Comment by TheJaredWilcurt** [comment]
Follow up, I tried specifying the Jest version as mentioned but the issue is still present.

* https://github.com/nwutils/nw-vue-cli-example/pull/44/files

I don't know how to say this in a kinder way, but saying to just not import a component used by the app just to get a test pass doesn't seem like a good solution. I still need that component to load in the app for the user. I shouldn't have to remove it to make the tests pass, since the app has no issues actually running the code, only the testing tools/setup have the problem. It is odd that removing the component is related though, as logically it being there or not *shouldn't* impact the rendering of native elements. Perhaps someone more knowledgeable than me could use that as a clue, but I'm not sure where to go from here with that information.

I have not tried with a new Vue-CLI generated project, as I have a lot of additional customizations on top to support desktop development and builds, I was hoping to avoid having to manually set those up again in a new project. But it seems that's the only direction I have left to go in now. I don't know if or when I'll ever have time to do that. Was really hoping I could just get some help with my set up.
